file_format: "1"
id: ergoddox
name: ErgoDDOX
type: shield
url: https://github.com/DidItWork/ergoddox/
requires: [pro_micro]
features:
  - keys
  - underglow
siblings:
  - ergoddox_left
  - ergoddox_right